### ISSUE TITLE
Error while getting dependencies from requirements.txt

### ISSUE THREAD

**Issue by DineshNanayakkara** [openai/web-crawl-q-and-a-example#3]
Hi,

I am not sure if this is something only happening on my end but wanted to post. 

I am getting the following error when I run, "pip install -r requirements.txt". 

Are the dependency versions correct?

**Comment by ItamarRocha** [comment]
Which error? It seems to be working fine. Could you double-check your environment?

**Comment by DineshNanayakkara** [comment]
Yeah, I am following the tutorial listed on the site.

Current error.
=========

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pydantic 2.5.1 requires typing-extensions>=4.6.1, but you have typing-extensions 4.4.0 which is incompatible.
pydantic-core 2.14.3 requires typing-extensions!=4.7.0,>=4.6.0, but you have typing-extensions 4.4.0 which is incompatible.

I managed to get it working by removing,
# typing_extensions==4.4.0
and by adding,
pydantic-core==2.14.3
typing-extensions>=4.6.1

Thanks.
